# Cadre

In [1]:
import numpy as np
np.__version__

'1.23.2'

In [21]:
t=np.ones((10,10),dtype=bool)
print(t)
imshow(t)
#marche pas

[[ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


NameError: name 'imshow' is not defined

In [19]:
def cadre(tab):
    #peux faire mieux à mon avis que "if", dans l'argument de la fonction par ex
    if tab.ndim == 2 :
        n=tab.shape[0]
        m=tab.shape[1]
        tab[1]=[0]*m
        tab[n-2]=[0]*m
        tab[:,1]=[0]*n
        tab[:,m-2]=[0]*n
        return tab
    else : 
        print("il faut tableau de dim 2")

In [20]:
print(cadre(t))

[[ True False  True  True  True  True  True  True False  True]
 [False False False False False False False False False False]
 [ True False  True  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True  True False  True]
 [False False False False False False False False False False]
 [ True False  True  True  True  True  True  True False  True]]


In [37]:
print(cadre(np.random.randint(0, 21, (6,8))))
#pas compris : type 'entier non signé sur 8bits'

[[ 3  0 13 10 14  7  0 18]
 [ 0  0  0  0  0  0  0  0]
 [ 4  0 20 16 15 13  0  3]
 [ 0  0 11 12 18  0  0 18]
 [ 0  0  0  0  0  0  0  0]
 [ 9  0 15  6  5 15  0  4]]


# Cadre 2

In [38]:
def cadre2(tab) :
    if tab.ndim == 2 :
        n=tab.shape[0]
        m=tab.shape[1]
        tab[0]=[0]*m
        tab[n-1]=[0]*m
        tab[:,0]=[0]*n
        tab[:,m-1]=[0]*n
        return tab
    else : 
        print("il faut tableau de dim 2")
#le choix de faire une copie ? pas compris la diff avec cadre1

# Anti_diagonal

In [48]:
def anti_diagonal(l) :
    t=np.zeros((len(l),len(l)))
    for i in range(len(l)):
        t[i][len(l)-1-i]=l[i]
    return t

In [49]:
print(anti_diagonal([1,2,3,4]))

[[0. 0. 0. 1.]
 [0. 0. 2. 0.]
 [0. 3. 0. 0.]
 [4. 0. 0. 0.]]


In [51]:
print(anti_diagonal([10]))
print(anti_diagonal([10,3]))

[[10.]]
[[ 0. 10.]
 [ 3.  0.]]


In [52]:
def anti_diagonal_2(l) :
    t=np.empty((len(l),len(l)))
    for i in range(len(l)):
        for j in range(len(l)):
            t[i][j]=0
    for i in range(len(l)):
        t[i][len(l)-1-i]=l[i]
    return t
#pas fan de ce que j'ai fait
#je ne vois pas vraiment comment ne pas utiliser de for

In [53]:
print(anti_diagonal_2([1,2,3,4]))

[[0. 0. 0. 1.]
 [0. 0. 2. 0.]
 [0. 3. 0. 0.]
 [4. 0. 0. 0.]]


## bonus

Pas compris, faudrait un entier en fait....

In [58]:
print(anti_diagonal((2,3,4,5)))
print(anti_diagonal({"a":1,"b":2,"c":3,"d":4}))
#tuple marche mais pas dictionnaire

[[0. 0. 0. 2.]
 [0. 0. 3. 0.]
 [0. 4. 0. 0.]
 [5. 0. 0. 0.]]


KeyError: 0

In [59]:
print(anti_diagonal(range(4)))

[[0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 2. 0. 0.]
 [3. 0. 0. 0.]]


In [60]:
print(anti_diagonal(x**2 for x in range(4)))

TypeError: object of type 'generator' has no len()

In [61]:
print(anti_diagonal([x**2 for x in range(4)]))

[[0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 4. 0. 0.]
 [9. 0. 0. 0.]]


In [64]:
print([x**2 for x in range(4)])
print(x**2 for x in range(4))
#Ca marche le 1er car ca créer une liste tout simplement
#Mais le 2e génère quelque chose 

[0, 1, 4, 9]
<generator object <genexpr> at 0x7f8a6a516890>
